-- Autonomous Ad Agency subsystem: inbound lead triage + client onboarding.
-- cuid() primary keys (text, app-generated by Prisma); org_id/project_id are
-- uuid to match organizations.id / projects.id. Tenant isolation via org_id.

CREATE TABLE IF NOT EXISTS client_profiles (
  id               text PRIMARY KEY,
  org_id           uuid NOT NULL,
  company_name     text NOT NULL,
  metro_area       text NOT NULL,
  phone            text,
  niche            text NOT NULL,
  brand_guidelines jsonb,
  project_id       uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  created_at       timestamp(6) NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_client_profiles_org_id ON client_profiles(org_id);

CREATE TABLE IF NOT EXISTS leads (
  id                text PRIMARY KEY,
  org_id            uuid NOT NULL,
  email             text NOT NULL,
  raw_body          text NOT NULL,
  intent_status     text NOT NULL,
  verification      jsonb,
  status            text NOT NULL DEFAULT 'PENDING',
  client_profile_id text UNIQUE REFERENCES client_profiles(id) ON DELETE SET NULL,
  created_at        timestamp(6) NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_leads_org_id_status ON leads(org_id, status);
