-- 013_landing_pages.sql
-- Landing / web pages per project. Generated by Claude as a self-contained
-- responsive HTML document (minimum credits: 0 Higgsfield credits — metered as
-- Claude tokens). Per-workspace quota is enforced in the app by account_type
-- (solo 1, sme 2, agency 20, admin unlimited). Additive + idempotent.
CREATE TABLE IF NOT EXISTS landing_pages (
  id         uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id     uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  title      text NOT NULL,
  brief      text,
  status     text NOT NULL DEFAULT 'queued',   -- queued | generating | ready | error
  html       text,
  error      text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_landing_pages_project ON landing_pages (project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_landing_pages_org     ON landing_pages (org_id);
CREATE INDEX IF NOT EXISTS idx_landing_pages_status  ON landing_pages (status);
