"use client";

import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";

/**
 * Project → Landing Pages. Request a self-contained responsive landing page,
 * generated by the runner (Claude → HTML, minimum credits — 0 Higgsfield
 * credits). Per-workspace quota by account type: solo 1 · sme 2 · agency 20 ·
 * admin unlimited. Preview renders inside a sandboxed iframe.
 */
type Page = { id: string; title: string; status: string; error: string | null; createdAt: string; updatedAt: string };
type Quota = { limit: number | null; used: number; remaining: number | null; accountType: string; isAdmin: boolean };

const STATUS_TONE: Record<string, string> = {
  ready: "bg-emerald-50 text-emerald-700", queued: "bg-amber-50 text-amber-700",
  generating: "bg-blue-50 text-accent", error: "bg-rose-50 text-rose-700",
};
const STATUS_LABEL: Record<string, string> = { ready: "Ready", queued: "Queued", generating: "Generating…", error: "Error" };

export default function LandingPagesPage() {
  const { id } = useParams<{ id: string }>();
  const [pages, setPages] = useState<Page[]>([]);
  const [quota, setQuota] = useState<Quota | null>(null);
  const [title, setTitle] = useState("");
  const [brief, setBrief] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [preview, setPreview] = useState<{ id: string; title: string; html: string } | null>(null);
  const pollRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const load = useCallback(async () => {
    try {
      const res = await fetch(`/api/projects/${id}/landing`);
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to load.");
      setPages(data.pages ?? []);
      setQuota(data.quota ?? null);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load.");
    } finally { setLoading(false); }
  }, [id]);
  useEffect(() => { load(); }, [load]);

  // Poll while anything is still generating.
  useEffect(() => {
    const busy = pages.some((p) => p.status === "queued" || p.status === "generating");
    if (pollRef.current) clearTimeout(pollRef.current);
    if (busy) pollRef.current = setTimeout(load, 5000);
    return () => { if (pollRef.current) clearTimeout(pollRef.current); };
  }, [pages, load]);

  const atQuota = quota != null && quota.limit != null && quota.used >= quota.limit;

  async function create(e: FormEvent) {
    e.preventDefault();
    setSaving(true); setError("");
    try {
      const res = await fetch(`/api/projects/${id}/landing`, {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title, brief }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Couldn't request the page.");
      setTitle(""); setBrief("");
      load();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Couldn't request the page.");
    } finally { setSaving(false); }
  }

  async function openPreview(p: Page) {
    try {
      const res = await fetch(`/api/projects/${id}/landing/${p.id}`);
      const data = await res.json();
      if (res.ok && data.html) setPreview({ id: p.id, title: p.title, html: data.html });
    } catch { /* non-fatal */ }
  }

  async function download(p: Page) {
    const res = await fetch(`/api/projects/${id}/landing/${p.id}`);
    const data = await res.json();
    if (!res.ok || !data.html) return;
    const blob = new Blob([data.html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${p.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase() || "landing-page"}.html`;
    document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url);
  }

  async function remove(p: Page) {
    if (!confirm(`Delete "${p.title}"? This frees a slot.`)) return;
    await fetch(`/api/projects/${id}/landing/${p.id}`, { method: "DELETE" });
    if (preview?.id === p.id) setPreview(null);
    load();
  }

  return (
    <div className="max-w-4xl">
      <Link href={`/dashboard/projects/${id}`} className="text-sm text-accent hover:underline">← Project</Link>
      <div className="mt-3 flex flex-wrap items-end justify-between gap-3">
        <div>
          <p className="font-mono text-xs uppercase tracking-widest text-accent">Graphics, Video &amp; Web</p>
          <h1 className="mt-1 font-display text-2xl font-bold tracking-tight">Landing pages</h1>
          <p className="mt-1 text-sm text-slate-500">Generate a complete, responsive landing page from a title and a short brief. Minimal cost — built as self-contained HTML.</p>
          <Link href="/dashboard/guides/publish-landing-page"
            className="mt-1 inline-flex items-center gap-1 text-sm font-medium text-accent hover:underline">
            How to publish on your own domain →
          </Link>
        </div>
        {quota && (
          <div className="rounded border border-slate-200 bg-white px-4 py-2 text-right">
            <div className="font-mono text-[11px] uppercase tracking-wider text-slate-400">Quota ({quota.accountType})</div>
            <div className="font-display text-lg font-bold tabular-nums text-slate-900">
              {quota.limit == null ? `${quota.used} · unlimited` : `${quota.used} / ${quota.limit}`}
            </div>
          </div>
        )}
      </div>

      {error && <p role="alert" className="mt-4 rounded bg-rose-50 px-3 py-2 text-sm text-rose-700">{error}</p>}

      {/* Request form */}
      <form onSubmit={create} className="mt-6 rounded border border-slate-200 bg-white p-5">
        <div className="grid gap-4">
          <div>
            <label className="font-mono text-[11px] uppercase tracking-wider text-slate-400">Page title</label>
            <input value={title} onChange={(e) => setTitle(e.target.value)} required maxLength={120}
              placeholder="e.g. Diwali Sale — 40% off refurbished laptops"
              className="mt-1 w-full rounded border border-slate-300 bg-slate-50 px-3 py-2 text-sm text-slate-900 focus:border-accent focus:outline-none" />
          </div>
          <div>
            <label className="font-mono text-[11px] uppercase tracking-wider text-slate-400">Brief (optional)</label>
            <textarea value={brief} onChange={(e) => setBrief(e.target.value)} rows={3} maxLength={4000}
              placeholder="Audience, offer, key benefits, tone, primary call-to-action…"
              className="mt-1 w-full rounded border border-slate-300 bg-slate-50 px-3 py-2 text-sm text-slate-900 focus:border-accent focus:outline-none" />
          </div>
        </div>
        <div className="mt-4 flex items-center gap-3">
          <button type="submit" disabled={saving || atQuota || !title.trim()}
            className="rounded bg-accent px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-accent-hover disabled:opacity-50">
            {saving ? "Requesting…" : "Generate page"}
          </button>
          {atQuota && (
            <span className="text-sm text-slate-500">
              You&apos;ve used all {quota?.limit} page{quota?.limit === 1 ? "" : "s"} on the {quota?.accountType} plan — delete one or upgrade to add more.
            </span>
          )}
        </div>
      </form>

      {/* List */}
      <div className="mt-6 overflow-hidden rounded border border-slate-200 bg-white">
        {loading ? (
          <p className="px-4 py-4 text-sm text-slate-500">Loading…</p>
        ) : pages.length === 0 ? (
          <p className="px-4 py-4 text-sm text-slate-500">No landing pages yet. Generate your first above.</p>
        ) : (
          <ul className="divide-y divide-slate-100">
            {pages.map((p) => (
              <li key={p.id} className="flex flex-wrap items-center justify-between gap-3 px-4 py-3">
                <div className="min-w-0">
                  <div className="truncate font-medium text-slate-800">{p.title}</div>
                  <div className="font-mono text-[11px] text-slate-400">{new Date(p.createdAt).toLocaleString("en-IN")}{p.error ? ` · ${p.error}` : ""}</div>
                </div>
                <div className="flex shrink-0 items-center gap-2">
                  <span className={`rounded px-2 py-0.5 text-xs font-medium ${STATUS_TONE[p.status] ?? "bg-slate-100 text-slate-500"}`}>{STATUS_LABEL[p.status] ?? p.status}</span>
                  {p.status === "ready" && (
                    <>
                      <button onClick={() => openPreview(p)} className="rounded bg-accent px-3 py-1.5 text-xs font-semibold text-white hover:bg-accent-hover">Preview</button>
                      <button onClick={() => download(p)} className="rounded border border-slate-300 px-2.5 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-100">Download</button>
                    </>
                  )}
                  <button onClick={() => remove(p)} className="rounded border border-rose-200 px-2.5 py-1.5 text-xs font-medium text-rose-600 hover:bg-rose-50">Delete</button>
                </div>
              </li>
            ))}
          </ul>
        )}
      </div>

      {/* Preview modal */}
      {preview && (
        <div className="fixed inset-0 z-50 flex flex-col bg-black/60 p-4" onClick={() => setPreview(null)}>
          <div className="mx-auto flex h-full w-full max-w-5xl flex-col overflow-hidden rounded-lg bg-white" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between border-b border-slate-200 px-4 py-2.5">
              <span className="truncate font-medium text-slate-800">{preview.title}</span>
              <button onClick={() => setPreview(null)} className="rounded px-2 py-1 text-sm text-slate-500 hover:bg-slate-100">Close ✕</button>
            </div>
            {/* Sandboxed: the generated HTML has no scripts, and sandbox="" blocks any anyway. */}
            <iframe title={preview.title} srcDoc={preview.html} sandbox="" className="h-full w-full flex-1 bg-white" />
          </div>
        </div>
      )}
    </div>
  );
}
