import { NextResponse } from "next/server";
import { getContext, isPlatformAdmin } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { webPageQuota } from "@/lib/billing/entitlements";
import { effectiveLandingPagesForPlan } from "@/lib/billing/pricing";

export const runtime = "nodejs";

/**
 * Landing / web pages for a project. Generated by the runner as a self-contained
 * responsive HTML document (Claude — minimum credits, 0 Higgsfield credits).
 * Per-workspace quota by account type: solo 1 · sme 2 · agency 20 · admin ∞.
 */
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
type Ctx = { params: { id: string } };

async function ensureProject(id: string, orgId: string) {
  if (!UUID.test(id)) return null;
  return prisma.projects.findFirst({ where: { id, org_id: orgId, deleted_at: null } });
}

/** The org's active plan slug (drives the landing quota), or null if none. */
async function activePlanSlug(orgId: string): Promise<string | null> {
  const sub = await prisma.subscriptions.findUnique({ where: { org_id: orgId } }).catch(() => null);
  return sub && (sub.status === "active" || sub.status === "trialing") ? sub.plan_slug : null;
}

/**
 * The workspace's landing-page quota. Admins are unlimited; an active plan uses
 * its admin-editable allowance (override → code default); otherwise the
 * account-type default applies.
 */
async function resolveLandingQuota(orgId: string, accountType: string | null, isAdmin: boolean): Promise<number> {
  const planSlug = await activePlanSlug(orgId);
  if (!isAdmin && planSlug) {
    const eff = await effectiveLandingPagesForPlan(planSlug);
    if (eff != null) return eff;
  }
  return webPageQuota(accountType, isAdmin, planSlug);
}

/** GET — list the project's landing pages + the workspace's quota usage. */
export async function GET(_request: Request, { params }: Ctx) {
  const { user, org } = await getContext();
  const project = await ensureProject(params.id, org.id);
  if (!project) return NextResponse.json({ error: "Not found." }, { status: 404 });

  const isAdmin = isPlatformAdmin(user.email);
  const quota = await resolveLandingQuota(org.id, org.account_type, isAdmin);
  const [pages, used] = await Promise.all([
    prisma.landing_pages.findMany({
      where: { project_id: project.id },
      orderBy: { created_at: "desc" },
      select: { id: true, title: true, status: true, error: true, created_at: true, updated_at: true },
    }),
    prisma.landing_pages.count({ where: { org_id: org.id } }),
  ]);

  return NextResponse.json({
    pages: pages.map((p) => ({
      id: p.id, title: p.title, status: p.status, error: p.error,
      createdAt: p.created_at.toISOString(), updatedAt: p.updated_at.toISOString(),
    })),
    quota: { limit: Number.isFinite(quota) ? quota : null, used, remaining: Number.isFinite(quota) ? Math.max(0, quota - used) : null, accountType: org.account_type, isAdmin },
  });
}

/**
 * POST — request a landing page. Body: { title, brief? }. Enforces the account
 * quota (admins unlimited), then enqueues it for the runner to generate.
 */
export async function POST(request: Request, { params }: Ctx) {
  const { user, org } = await getContext();
  const project = await ensureProject(params.id, org.id);
  if (!project) return NextResponse.json({ error: "Not found." }, { status: 404 });

  const isAdmin = isPlatformAdmin(user.email);
  const quota = await resolveLandingQuota(org.id, org.account_type, isAdmin);
  const used = await prisma.landing_pages.count({ where: { org_id: org.id } });
  if (used >= quota) {
    return NextResponse.json({
      error: `Your plan includes ${quota} landing page${quota === 1 ? "" : "s"}. Delete one or upgrade to add more.`,
      code: "QUOTA",
    }, { status: 403 });
  }

  const body = (await request.json().catch(() => ({}))) as { title?: unknown; brief?: unknown };
  const title = typeof body.title === "string" ? body.title.trim() : "";
  if (!title) return NextResponse.json({ error: "A page title is required." }, { status: 400 });
  const brief = typeof body.brief === "string" ? body.brief.trim().slice(0, 4000) : "";

  const page = await prisma.landing_pages.create({
    data: { org_id: org.id, project_id: project.id, created_by: user.id, title, brief, status: "queued" },
    select: { id: true, title: true, status: true, created_at: true },
  });
  return NextResponse.json({ page: { id: page.id, title: page.title, status: page.status, createdAt: page.created_at.toISOString() } }, { status: 201 });
}
