import { LegalDoc, type Block } from "@/components/legal/LegalDoc";
import { LEGAL } from "@/lib/legal";

export const metadata = { title: "Acceptable Use & Disclaimer · SkirrNow" };

const blocks: Block[] = [
  {
    h: "1. Purpose",
    p: [
      `This Acceptable Use & Disclaimer policy governs what you may and may not do with ${LEGAL.brand} (the “Service”) and what you can and cannot expect from AI-generated outputs. It forms part of our Terms of Use.`,
    ],
  },
  {
    h: "2. Prohibited uses",
    p: ["You must not use the Service, or any output from it, to create, promote, or distribute:"],
    ul: [
      "Anything unlawful, or content that promotes illegal activity.",
      "Deceptive, false, or misleading advertising, fake reviews, or unsubstantiated claims about a product or service.",
      "Content that infringes another party's intellectual-property, publicity, or privacy rights.",
      "Hateful, harassing, defamatory, or violent content, or content that targets protected groups.",
      "Sexual content involving minors, or any child sexual abuse material — under any circumstances.",
      "Adult sexual content, where prohibited by law or by our providers.",
      "Malware, phishing, scams, or content designed to defraud or harm people.",
      "Impersonation of a person, brand, or organisation without authorisation.",
      "Spam, or bulk unsolicited messaging in violation of applicable communications law.",
      "Regulated claims (for example health, financial, or legal claims) without the substantiation and disclosures the law requires.",
    ],
  },
  {
    h: "3. Platform integrity",
    ul: [
      "Do not attempt to breach, probe, or overload the Service, its infrastructure, or its rate limits and credit controls.",
      "Do not scrape, resell, or provide the Service to third parties except as expressly permitted.",
      "Do not use the Service to build a competing product, or to reverse-engineer our systems.",
    ],
  },
  {
    h: "4. Your responsibilities with AI output",
    ul: [
      "You are the publisher. Before you use or publish an output, review it and verify every factual and promotional claim.",
      "Ensure your final material complies with applicable advertising, consumer-protection, and industry rules (for example advertising standards and sector-specific regulations that apply to you).",
      "Where the law requires disclosures, obtain them and include them; the Service does not do this for you.",
    ],
  },
  {
    h: "5. Disclaimer",
    p: [
      'Outputs generated by the Service — including ad copy, images, videos, and landing pages — are produced by automated AI systems and are provided "as is". They may be inaccurate or incomplete and must be checked before use.',
      "Outputs are drafts and creative assistance only. They are not professional, legal, financial, medical, or regulatory advice, and nothing in an output should be relied upon as such. We make no guarantee of any particular result, ranking, conversion, or commercial outcome from using the Service.",
    ],
  },
  {
    h: "6. Enforcement",
    p: [
      "We may remove content, and suspend or terminate accounts, that we reasonably believe violate this policy or applicable law. Serious or repeated violations may be reported to the relevant authorities.",
    ],
  },
  {
    h: "7. Reporting and contact",
    p: [
      `To report misuse, or for questions about this policy, contact ${LEGAL.contactEmail}. ${LEGAL.entity}, ${LEGAL.address}.`,
    ],
  },
];

export default function AcceptableUsePage() {
  return (
    <LegalDoc
      title="Acceptable Use & Disclaimer"
      intro="The rules for using SkirrNow responsibly, and what to understand about AI-generated outputs."
      blocks={blocks}
    />
  );
}
